import { DebridAccount, RealDebridClient, DebridUnrestrictResult } from './realdebrid-client';
import { TorboxClient } from './torbox-client';

export class DebridOrchestrator {
  private rdClient: RealDebridClient | null = null;
  private tbClient: TorboxClient | null = null;
  private activeProvider: 'realdebrid' | 'torbox' | null = null;

  constructor() {
    this.loadAccounts();
  }

  /**
   * Load saved API keys from localStorage
   */
  private loadAccounts() {
    try {
      const saved = localStorage.getItem('tatakai_debrid_accounts');
      if (saved) {
        const accounts: DebridAccount[] = JSON.parse(saved);
        
        const rd = accounts.find(a => a.provider === 'realdebrid' && a.isActive);
        if (rd?.apiKey) {
          this.rdClient = new RealDebridClient(rd.apiKey);
          this.activeProvider = 'realdebrid';
        }

        const tb = accounts.find(a => a.provider === 'torbox' && a.isActive);
        if (tb?.apiKey) {
          this.tbClient = new TorboxClient(tb.apiKey);
          // Torbox overrides RD if both are active (preference can be made configurable later)
          if (!this.activeProvider) this.activeProvider = 'torbox';
        }
      }
    } catch (err) {
      console.error('[DebridOrchestrator] Failed to load accounts', err);
    }
  }

  /**
   * Save API keys to localStorage
   */
  saveAccounts(accounts: DebridAccount[]) {
    localStorage.setItem('tatakai_debrid_accounts', JSON.stringify(accounts));
    this.loadAccounts(); // reload clients
  }

  getAccounts(): DebridAccount[] {
    try {
      const saved = localStorage.getItem('tatakai_debrid_accounts');
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  }

  hasActiveProvider(): boolean {
    return this.activeProvider !== null;
  }

  getActiveProviderName(): string | null {
    return this.activeProvider;
  }

  /**
   * Fully resolve a magnet link into a direct streamable HTTP URL using the active debrid provider.
   * This handles the complex process of adding, selecting, and unrestricting the file.
   */
  async resolveMagnetToStream(magnet: string): Promise<string> {
    if (!this.activeProvider) {
      throw new Error('No active debrid provider configured');
    }

    if (this.activeProvider === 'realdebrid' && this.rdClient) {
      // 1. Add Magnet
      const id = await this.rdClient.addMagnet(magnet);
      
      // 2. Wait for RD to parse the magnet (usually instant if cached, but we should poll)
      let info = await this.rdClient.getTorrentInfo(id);
      let retries = 0;
      while (info.status === 'magnet_conversion' && retries < 10) {
        await new Promise(r => setTimeout(r, 1000));
        info = await this.rdClient.getTorrentInfo(id);
        retries++;
      }

      if (info.status === 'magnet_conversion') {
        throw new Error('Magnet conversion timed out on Real-Debrid');
      }

      // 3. Find the largest video file
      const videoFiles = info.files.filter((f: any) => 
        f.path.endsWith('.mp4') || f.path.endsWith('.mkv') || f.path.endsWith('.avi')
      ).sort((a: any, b: any) => b.bytes - a.bytes);

      if (videoFiles.length === 0) {
        throw new Error('No video files found in the torrent');
      }

      // 4. Select the file
      await this.rdClient.selectFiles(id, [videoFiles[0].id.toString()]);

      // 5. Unrestrict the generated link
      // Wait for the link to be generated
      info = await this.rdClient.getTorrentInfo(id);
      retries = 0;
      while ((!info.links || info.links.length === 0) && retries < 10) {
        await new Promise(r => setTimeout(r, 1000));
        info = await this.rdClient.getTorrentInfo(id);
        retries++;
      }

      if (!info.links || info.links.length === 0) {
         throw new Error('No links generated by Real-Debrid');
      }

      const unrestrictResult = await this.rdClient.unrestrictLink(info.links[0]);
      return unrestrictResult.url;
    }

    if (this.activeProvider === 'torbox' && this.tbClient) {
        // Very simplified Torbox flow (actual flow might require caching checks)
        const torrentId = await this.tbClient.addMagnet(magnet);
        if (!torrentId) throw new Error('TorBox failed to add magnet');
        
        // Wait for processing
        await new Promise(r => setTimeout(r, 2000));
        
        const info = await this.tbClient.getTorrentInfo(torrentId);
        
        // Find largest file ID
        const fileId = '1'; // Placeholder: proper implementation needs Torbox specific file ID extraction
        
        const result = await this.tbClient.unrestrictLink(torrentId, fileId);
        return result.url;
    }

    throw new Error('Active provider client not initialized');
  }
}

export const debridOrchestrator = new DebridOrchestrator();
