// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const VITE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Standardize URL to avoid framing/CORS blocks on custom domains
// Project Ref: xkbzamfyupjafugqeaby
const SUPABASE_URL = (VITE_SUPABASE_URL?.includes("jiobase.com") || !VITE_SUPABASE_URL)
  ? "https://xkbzamfyupjafugqeaby.supabase.co"
  : VITE_SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});