const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
    getPlatform: () => ipcRenderer.invoke('get-platform'),
    updateRPC: (data) => ipcRenderer.send('update-rpc', data),
    notify: (data) => ipcRenderer.send('notify', data),
    onNavigate: (callback) => ipcRenderer.on('navigate', (event, path) => callback(path)),
    startDownload: (payload) => ipcRenderer.invoke('start-download', payload),
    cancelDownload: (params) => ipcRenderer.invoke('cancel-download', params),
    deleteAnime: (animePath) => ipcRenderer.invoke('delete-anime', animePath),
    getDownloadsDir: (customPath) => ipcRenderer.invoke('get-downloads-dir', customPath),
    getOfflineLibrary: (customPath) => ipcRenderer.invoke('get-offline-library', customPath),
    syncOfflineLibrary: (customPath) => ipcRenderer.invoke('sync-offline-library', customPath),
    importVideoFiles: () => ipcRenderer.invoke('import-video-files'),
    openDownloadsFolder: (customPath) => ipcRenderer.invoke('open-downloads-folder', customPath),
    repairAnime: (params) => ipcRenderer.invoke('repair-anime', params),
    selectDirectory: () => ipcRenderer.invoke('select-directory'),
    openPath: (path) => ipcRenderer.invoke('open-path', path),
    invoke: (channel, data) => ipcRenderer.invoke(channel, data),
    onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (event, data) => callback(data)),
    onDownloadCompleted: (callback) => ipcRenderer.on('download-completed', (event, data) => callback(data)),
    onDownloadError: (callback) => ipcRenderer.on('download-error', (event, data) => callback(data)),
    onToggleLogViewer: (callback) => ipcRenderer.on('toggle-log-viewer', () => callback()),
    minimize: () => ipcRenderer.send('window-minimize'),
    maximize: () => ipcRenderer.send('window-maximize'),
    close: () => ipcRenderer.send('window-close'),
    log: (level, message, data) => ipcRenderer.send('log', { level, message, data }),
    exportLogs: () => ipcRenderer.invoke('export-logs'),
    checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    quitAndInstall: () => ipcRenderer.invoke('quit-and-install'),
    onUpdaterEvent: (callback) => ipcRenderer.on('updater-event', (event, data) => callback(data)),
    resetAppData: () => ipcRenderer.invoke('reset-app-data'),
    setAutoLaunch: (enabled) => ipcRenderer.invoke('set-auto-launch', enabled),
    getAutoLaunch: () => ipcRenderer.invoke('get-auto-launch'),
    getSystemInfo: () => ipcRenderer.invoke('get-system-info'),
    getClientId: () => ipcRenderer.invoke('get-client-id'),
    openDevTools: () => ipcRenderer.send('open-devtools'),
});
